### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#100]
Yeah...

We should really reach out to an artist and get a better logo.

**Comment by 32th-System** [comment]
ideally the logo should be designed to work with the website's general design

**Comment by jgdhs27** [comment]
What's the status of the 'redesign'? Personally I feel this can be tackled independently of redesigning the site

**Comment by 32th-System** [comment]
well, I feel like if the site has mostly pink, purple and darker grey colors, a logo made entirely out of shades of green wouldn't really fit in

**Comment by jgdhs27** [comment]
Its also a question of priorities for me. I feel the current design is good enough and a redesign isnt so important - but the logo really needs to change

**Comment by n-rook** [comment]
I don't really think we should be thinking about the redesign as being a big top down revamp. I personally like the current color scheme, and it fits the site theme (because they're Patchouli's colors).

**Comment by jgdhs27** [comment]
A new logo was added in #332
