### ISSUE TITLE
th08 spell practice replays broken (and possibly other games)

### ISSUE THREAD

**Issue by raviddog** [n-rook/thscoreboard#138]

**Comment by n-rook** [comment]
how broken is it?

imo we should just block all practice replays (and vs mode) until we're actually ready to build out the pages on the frontend to view them well. I can't imagine anyone is particularly invested in us supporting them or not; we can worry about replacing lunarcast etc after we've already got everything necessary to be a great scoreboard

**Comment by raviddog** [comment]
one gave 32th's lzss error, one crashed.
I suspect the header has something we didnt't account for

**Comment by n-rook** [comment]
ah I see

yeah, that needs work then, even to correctly detect them and then send errors back to the user

**Comment by raviddog** [comment]
I think we want to add tests for practice, spell practice, thprac replays for all currently supported games before we open closed beta

**Comment by 32th-System** [comment]
thprac replays are the same as practice/spell practice replays but with a bit of extra JSON data at the end. As for the crashing issue, `bytearray(rep_raw[24:])` includes the USER section, which gets run through the decryption even though it's not encrypted

**Comment by 32th-System** [comment]
I'm gonna need the replay that caused the LZSS error for a test

**Comment by raviddog** [comment]
#148
