### ISSUE TITLE
Support IP bans

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#144]
IP bans are good so that if someone's really trying to sabotage the website, we can block them. I think this is the only thing we really need to go from closed beta to open beta.

- [x] Receive and log IP addresses on the server (rather than just logging 127.0.0.1 from nginx)
- [x] Record IP addresses and their relationship with the logged-in user, but delete them after some amount of time
- [ ] Implement IP bans

**Comment by 32th-System** [comment]
At the moment we don't even have normal bans

**Comment by n-rook** [comment]
I think IP bans are actually more of a priority than normal bans; plus we need them to support normal bans (so we have some recourse if the banned user makes a new account)

**Comment by n-rook** [comment]
Thinking about it more, I don't think we need to actually implement ip bans on the server itself. As long as we record the ips, we can just enforce them in nginx (and indeed nginx is the right place to put them)
