### ISSUE TITLE
Don't have local changes to the staging repository on the server

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#152]
Right now, if I want to go mess around with staging, I have to be sure not to accidentally revert the "real" changes when I do so. I brought down staging by accident by doing this once.

**Comment by 32th-System** [comment]
Fixed by https://github.com/n-rook/thscoreboard/commit/4e77caa36dc601b15070de08418e5b244ac7878b and `cp uwsgi.ini uwsgi-staging.ini`
