### ISSUE TITLE
Log in page background looks weird

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#166]
<img width="814" alt="Screen Shot 2022-12-24 at 1 34 08 PM" src="https://user-images.githubusercontent.com/9295955/209447688-9b724a76-a2f9-4993-be78-5d7a56db51a2.png">

This is my fault, I think I just broke this

**Comment by 32th-System** [comment]
Also affects the background for the "you have logged out" page. On the dark theme it's dark purple
