### ISSUE TITLE
pressing back and re-uploading a replay does bad things

### ISSUE THREAD

**Issue by raviddog** [n-rook/thscoreboard#173]
temp replay isnt there anymore, it throws a 404, we should handle this more gracefully

**Comment by 32th-System** [comment]
Could you check this again? Because this doesn't seem to be happening anymore

**Comment by raviddog** [comment]
The debug page scared me, I checked the actual 404 and a user can just click the banner to go home. I do think adding text to explicitly say "go back to the main page" or something will help though.

**Comment by 32th-System** [comment]
No the thing is that the temp replay was still there for me when going back and can easily be accessed again

**Comment by raviddog** [comment]
Maybe bad wording on the title, I completed the upload and then pressed back

**Comment by 32th-System** [comment]
Oh. Well that issue would be fixed by https://github.com/n-rook/thscoreboard/pull/262 actually

**Comment by n-rook** [comment]
yeah this would be fixed by #262. it could easily be fixed by the existing schema too though; you'd just have to add a column to the replay table for the temp id the replay previously had (if any), put an index on it, and use it to redirect to the final upload page

**Comment by raviddog** [comment]
Don't think this is important anymore, closing
