### ISSUE TITLE
Remove private replays

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#184]
Private replays are kind of pointless, and an extra category just makes the site more confusing. (After all, why would someone want to use the site if they don't want to share replays with other people?)

**Comment by raviddog** [comment]
I can think of reasons, like using it for backup purposes or if they just don't want to be involved with the community. How much more complicated does keeping this feature make things?

**Comment by n-rook** [comment]
My main concern with it was that it added complexity to the web design. We already have three different categories of replays: regular, tool-assisted and unusual (aka "anything else"); adding a fourth kind is something else users have to keep in mind. I know I've heard from people who are intimidated by how many options Lunarcast has. And I'm just not convinced it would really be useful to people.

If we did support private replays, I actually think the current implementation isn't good anyway. "private" isn't really a category in the way regular, TAS etc., are; it's really a different dimension altogether.

**Comment by raviddog** [comment]
makes sense, so if we ever wanted to add it in the future it would need a separate framework rather than the implementation we currently have, gotcha
