### ISSUE TITLE
Short game names aren't getting displayed properly

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#202]
For example:

![image](https://user-images.githubusercontent.com/9295955/217063912-c1c65a91-5762-4b3d-b8af-ef84b4d05227.png)

These should be "EoSD", "MoF" etc.

**Comment by n-rook** [comment]
Fixed

![image](https://user-images.githubusercontent.com/9295955/218286505-b0bf9d3e-1149-4762-b646-e1da501f6a56.png)

**Comment by n-rook** [comment]
Fixed
![fixed names](https://user-images.githubusercontent.com/9295955/218286524-acba3368-6a2e-4c02-aa70-d3d1286cd276.png)

**Comment by 32th-System** [comment]
Erm, I see nothing wrong with the first screenshot. I guess it's a preference thing

**Comment by n-rook** [comment]
there wasn't really anything wrong with it per se, but it was supposed to look like the second screenshot all along, so that's why I marked it as a bug
