### ISSUE TITLE
Allow users to delete their accounts

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#203]
It is currently not possible for users to delete their own accounts.

We need to be careful about how to implement this, but I think it is clearly something we should implement, both for legal and ethical reasons.

**Comment by 32th-System** [comment]
Regarding the implementation, I have these questions that I think should all be answered for the implementation. There might be more, but these are the ones I can think of
- How should old replays from the deleted user be affected?
- What should happen with the username? How long until someone else could use that name?
- What if the same person wants to sign up again? We can verify if it's the same person who wants to sign up again based on the e-mail address. What if the username of a deleted account is up for grabs again but the person who deleted again wants to sign up again with that name? How should that affect the other person who took the name?
- What about regular bans? In what ways should the answers to the above questions change if it's not a regular account deletion but a regular ban?

**Comment by n-rook** [comment]
Those are good questions. I'll lay out my design here.

Deleting an account should delete all information related to the account. This includes all of the user's replays. It's unfortunate to lose information like that, but I don't think it's right to keep that data if the person doesn't want us to have it anymore. Similarly, the username will become available if a new user wants it. (The email address will be available too, in case the user decides to come back.)

We should not immediately delete an account on request. After all, the user might change their mind a few days later. Or, the account might have been hacked, and the person behind it might not actually want it to be deleted. Instead, we should mark the account as "to be deleted". While the account is "to be deleted", the user can still log in, but the only thing they should be able to do is tell us they changed their mind and don't want the account deleted anymore.

If an account is in the "to be deleted" state, of course the username can't be reused, but we should make it similar to the account really being deleted in all other respects; notably, we should hide the replays so it looks like they were deleted.

If someone deletes their account, and someone else takes the username, and then the first person wants to come back with the username, too bad: it now belongs to the second person. I think this is the only sensible way to handle things. (This is why I want a "grace period" before actually deleting the account, so if the user has a change of heart they can keep their account.)

For bans, I think it's important to let the banned user delete their account, but it's just as important to not let them use this to get around a ban. So, I think if a banned user tries to delete their account, we should delete the user information, replays and so on, but keep their username and email address in a new "banned users" table, so they can't be reused. (I do think we are fine here from a GDPR standpoint.)

**Comment by 32th-System** [comment]
question about the "to be deleted" state: do the replays stay visible or should they be put in a state similair to private replays?

**Comment by n-rook** [comment]
They're hidden, like private replays: we want the account to look like it was deleted, after all. We just keep the replays around in case the user changes their mind.

I'll have a PR out on this later today.

**Comment by 32th-System** [comment]
Regarding bans, and account deletion: we're gonna have to specify somewhere that information for banned users might have to be kept for a bit longer to prevent ban evasion, but we also can't keep information forever in case of permanent bans. If we want to ban someone permanently, they'll still be able to delete their account and the information should still disappear from our server, but to prevent ban evasion we would need to use IP bans

**Comment by n-rook** [comment]
For bans, I was thinking that we would allow them to delete most information, but keep their username, email address, and reason for being banned. We could accomplish this technically by recording username and email address in the row of the ban table itself, but deleting the row in the user table.

I was thinking that we could keep these ban rows for a long time, such as 15 years. Since we are only keeping the minimal information required to sustain the ban, we will have a strong argument that we have compelling legitimate grounds to keep this information.
