### ISSUE TITLE
Schedule delete_old_data

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#204]
There is a management command called delete_old_data that deletes certain old data. However, we do not actually run it in production at this time. We should hook this up to a cron job somehow and actually use it.

**Comment by 32th-System** [comment]
at what interval should it run?

**Comment by 32th-System** [comment]
I have backups scheduled to be daily, which is also an expensive operation. I guess I could schedule `delete_old_data` to run after the backup

**Comment by n-rook** [comment]
Up to you. I'd probably schedule it separately, just so that one breaking doesn't affect the other (and we can get their logs separately)
