### ISSUE TITLE
Design and implement a ban system

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#205]
We need the ability to temporarily or permanently ban users if they cause trouble on the site.

We already support "IP bans", but I think we should support regular bans too, especially temporary bans. An IP ban is a big hammer and we should only use it if people are evading regular bans. (Not that an IP ban is impossible to evade either.)

Supporting temporary bans is especially good because it lets us get people off the site if they are causing trouble without preventing them from ever using it again.

**Comment by 32th-System** [comment]
the main thing the IP ban system does is prevent sign ups. Therefore, we need a way to restrict already signed up accounts
