### ISSUE TITLE
Rename "regular" replay type or category

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#216]
Currently, both replay type and category have an option called "Regular", which is insanely confusing. We should rename one of them.

Actually, I don't like "regular" for either name, now that I think about it, so I'd be down to rename both.

The "Regular" replay type is in contrast to stage practice, spell practice, and so on. For this one, we should pick a name that makes it obvious what it is. Maybe "Full Run" or "Full Game"?

The category is in contrast to "Tool-Assisted". For this one, maybe "Standard"? As in, "played according to standards".

**Comment by raviddog** [comment]
Was thinking standard or normal, but default might be a good one
Or we can rename it to Special Category and then the default would be None which would make more sense to most people I think
