### ISSUE TITLE
Strange, negative-slowdown SA replay can't be uploaded

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#235]
[th11_udAAAA.zip](https://github.com/n-rook/thscoreboard/files/10714958/th11_udAAAA.zip)

Thanks to Nylilsa for the report.

This odd replay has a negative slowdown rate and is rejected by Silent Selene. Apparently this weird negative slowdown can be reproduced by holding Z while exiting the replay menu.

We should accept all replays, even weird ones like this!

**Comment by raviddog** [comment]
Removing the try catch, it appears to be a decryption error, line 500 in replay_parsing
@32th-System
