### ISSUE TITLE
Suggest legal user replay names for downloaded replays

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#237]
When replays are downloaded, we should have them be downloaded in a legal "user replay" format.

I think we should stick with the current format for mof since user replays are broken there, but for everything else, we should suggest names that would allow them to be used as user replays.

**Comment by 32th-System** [comment]
When you say suggest do you mean something like having a second download button that downloads replays in the form of `thXX_udXXX.rpy` or to just have the existing download button use that format instead of the current one?

**Comment by n-rook** [comment]
The latter
