### ISSUE TITLE
Parse the year of play from th08 replays

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#242]
https://www.silentselene.net/replays/th08/25

![image](https://user-images.githubusercontent.com/9295955/218287711-8e7ff735-abb1-45dc-aa5d-5bdd17fc0f5c.png)
Reported by Rivers

**Comment by raviddog** [comment]
The full timestamp isn't present in the replay header that the game reads from, thus it isn't shown ingame which is why I didn't realise it had it. I'll change it to read from the userdata.
