### ISSUE TITLE
stage orders are bugged

### ISSUE THREAD

**Issue by raviddog** [n-rook/thscoreboard#257]
th6-9: 1 indexed
\>th10: 0 indexed
also any replays already existing that get reanalyzed end up with the wrong order, since the DB pulls in terms of row id first
so they need to be sorted by stage num before being used

related to incomplete fix for #181
see additional comment there
primarily caused by GetFormatStage in game_fields.py not being updated accordingly

**Comment by n-rook** [comment]
for stage order the fix is probably to make an index for replay stages (sort by replay id then stage num) and to sort by those two (in order) by default
