### ISSUE TITLE
redo the replay section of the database

### ISSUE THREAD

**Issue by raviddog** [n-rook/thscoreboard#29]
potential layout
ignore the types and nulls i gave up halfway
![image](https://user-images.githubusercontent.com/6138276/186765923-c391dcab-1603-4dae-8cef-bf872b79a797.png)

also heres a list of game specific stage fields

- th06_rank
- th07_cherry
- th07_cherrymax
- th08_time
- th08_human/youkai
- th09_char
- th09_ai
- th12_ufo1
- th12_ufo2
- th12_ufo3
- th125_freeze_area
- extends
- th13_trance
- th14_poc_count
- th14_miss_count
- th16_season
- th17_hyper_fill
- th17_token1
- th17_token2
- th17_token3
- th17_token4
- th17_token5

**Comment by n-rook** [comment]
I don't think "redo the table" is really the right way to think about it. The table works now, after all. We should change and improve it gradually to implement new features or to fix specific existing problems with it (like the fact that there's data in the replay file table).

**Comment by raviddog** [comment]
well however the phrasing is interpreted, it needs to be adjusted gradually to match the data fields we require from it

**Comment by raviddog** [comment]
#54
