### ISSUE TITLE
Error thrown when parsing username from replay

### ISSUE THREAD

**Issue by jgdhs27** [n-rook/thscoreboard#322]
In the relay parsers, the following error is thrown on certain replays:
`'ascii' codec can't decode byte 0xa5 in position 3: ordinal not in range(128)`

Guess: this happens when the username in the replay contains a space.

Example of a failing replay: http://replay.lunarcast.net/replay/th6_ud5071.rpy

**Comment by jgdhs27** [comment]
This is the exact line that causes the bug:
`            self.name = (KaitaiStream.bytes_terminate(self._io.read_bytes(9), 0, False)).decode(u"ASCII")`

**Comment by 32th-System** [comment]
what if you try to use SJIS instead of ASCII??

**Comment by jgdhs27** [comment]
that fixes it!

**Comment by jgdhs27** [comment]
am i remembering correctly that the .py files (like `th06.py`) aren't 100% generated from the kaitai parsers?

**Comment by 32th-System** [comment]
Yeah there's one line in th06.py that the parser puts inside a loop that is manually moved out of the loop

**Comment by jgdhs27** [comment]
There seems to be another related issue for th10 onwards:
in `th_modern.py`, the line `            self.user_desc = (self._io.read_bytes_term(13, False, True, True)).decode(u"SJIS")`
throws `'shift_jis' codec can't decode byte 0xec in position 6: illegal multibyte sequence`
