### ISSUE TITLE
20% of Royalflare imports failing due to corrupted replay headers

### ISSUE THREAD

**Issue by jgdhs27** [n-rook/thscoreboard#324]
Many royalflare replays cannot be imported due to their headers being corrupted. For example, http://replay.lunarcast.net/replay/th11_ud5072.rpy About 20% of royalflare replays from th10 onwards are affected. Because the amount of affected replays is so high, we should figure out how to import them (and possibly even fix them). The replays work fine in-game.

**Comment by raviddog** [comment]
I've got a solution in the works, but could someone source some TH13 and TH14 replays for me to check, because this string is how we determine which game those are from and if that gets messed up then gee thanks ZUN I don't know how we'll do this.

**Comment by n-rook** [comment]
Nice!
