### ISSUE TITLE
If I visit https://www.silentselene.net/#, the table doesn't load

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#333]
https://www.silentselene.net/#

This is kind of an odd one. The theme switcher currently goes to this URL, so it's not good that it breaks the data loader for some strange reason.

**Comment by 32th-System** [comment]
It's this code right here
```js
  const xhr = new XMLHttpRequest();
  if(window.location.pathname === '/') {
    xhr.open('GET', window.location.href + 'replays/index/json', true);
  } else {
    xhr.open('GET', window.location.toString() + "/json", true);
  }
```
Something like https://www.silentselene.net/replays/th18# is also broken
