### ISSUE TITLE
General contact information(?)

### ISSUE THREAD

**Issue by KirbyComment** [n-rook/thscoreboard#357]
As far as I know there's no "general" contact information or any place from the website from which you can access the Silent Selene Discord server. There's only _privacy@silentselene.net_ on the Privacy Policy page. Should there be some e-mail to let outsiders contact developers about general questions?

When discussing HRtP default lives rule with Karisa, there was no general contact method for her to get in touch with you guys - only with individual developers (https://www.shrinemaiden.com/index.php?topic=46.msg28127#msg28127)

**Comment by n-rook** [comment]
This makes sense.

I had been hesitant to add a public Discord link to our server, for fear of attracting bots, but an email makes sense. Plus I can throw the Gap under the bus and provide a public link to them, and then say that people should join through there.
