### ISSUE TITLE
Replays uploaded as "tool assisted" aren't labeled properly

### ISSUE THREAD

**Issue by KirbyComment** [n-rook/thscoreboard#362]
While replays labeled as "tool assisted" don't show up in the main list of replays like it should, selecting this replay to view details shows the replay with the type "Regular".

![image](https://user-images.githubusercontent.com/129665085/235297010-3cd6904d-69db-46bb-86cc-e23f421b407d.png)

**Comment by n-rook** [comment]
This is #216
