### ISSUE TITLE
dev-only requirements.txt file

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#37]
There are a few modules that are required at build or compile time but not at runtime. As such they shouldn't actually be deployed. We should write a separate requirements.txt including them.

**Comment by raviddog** [comment]
kaitai-struct isnt needed at runtime, what else though

**Comment by n-rook** [comment]
stuff like flake8, or libraries only used by tests (I don't think there are any like that right now, but we might want freezegun at some point)
