### ISSUE TITLE
Bad performance when loading a large amount of replays

### ISSUE THREAD

**Issue by jgdhs27** [n-rook/thscoreboard#370]
Performance on https://www.silentselene.net/replays/th08 is bad. Loading the json takes about 1.7s. On my local setup, the request takes just 0.35s.

One possible improvement would be to stream the json data, or at lest load it in batches.
As a starting point: some time ago I tried modifying the API calls to first load just the first 50 files, and then load the remaining files. The code for that is on [this branch](https://github.com/jgdhs27/thscoreboard/tree/api-speedup). This worked but had no measurable performance impact. I can imagine it'll help on a non-local setup.

It would also help to request replays immediately (see issue #351)

**Comment by jgdhs27** [comment]
Also consider reducing the amount of data sent. This could be done by compressing, or by removing unnecessary data. Maybe the data should be in csv format or similar.

**Comment by n-rook** [comment]
I think gzip is probably the first thing to try. json tends to be very compressible. I suspect this will have a significant benefit.

**Comment by jgdhs27** [comment]
With #373 and #390 landed I consider this fixed.
