### ISSUE TITLE
embiggen disk

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#376]
disk is 17G/25G right now, we should get more disk space. I suspect disk space is cheap. if not we can think about other ways to get more disk (remove most rf replays from staging, for example) but this is the simplest way I can think of

**Comment by 32th-System** [comment]
I did a disk cleanup before. I used `du` to find the things that used the most disk space and if we didn't need it I cleaned it out. One thing that was using a lot of space were the systemd logs

**Comment by n-rook** [comment]
oh interesting. we should probably set up a ttl on the systemd logs somehow too then

**Comment by n-rook** [comment]
Disk is 55GB now
