### ISSUE TITLE
Figure out where to host the site in the medium term

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#45]
Currently, we're using Heroku's free tier to host the site. However, Heroku is taking away their free tier in November. This would be unfortunate for us. We want to pay for our production site anyway (their free offering isn't good enough), but it'd be pointlessly expensive to pay for staging. The pricing would be something like:

$7/mo for one production dyno
$7/mo for one staging dyno (pointless!)
$9/mo for production database
$9/mo for staging database (pointless!)

See https://www.heroku.com/pricing.

Plus, Heroku doesn't offer automated backups.

So, I think we should probably think about moving somewhere other than Heroku. Requirements are:

- Hopefully pretty cheap; I think this project should not take a lot of resources
- Hopefully has a really cheap box available for staging
- Hopefully can run both prod and staging databases on the same box. This is obviously possible if we actually roll our own Postgres, but may or may not be possible with managed solutions
- Automated backups are required

**Comment by 32th-System** [comment]
![grafik](https://user-images.githubusercontent.com/23106652/188752791-a7d5dfae-909c-486f-97b5-211e6cb6e303.png)
https://www.ovhcloud.com/en/vps/

**Comment by n-rook** [comment]
That's cheap as fuck, I think 2 vCore/4 GB is pretty much what we would need. Googling OVHCloud gets some... mixed reviews though, and those bandwidth limits are actually really low. But it really is cheap. vultr is $20/mo for a comparable offering.

I agree that we will probably want to run a VPS rather than a platform-as-a-service company so we can save money. We can always just run Docker ourselves rather than paying somebody else to do it for us.

**Comment by raviddog** [comment]
are we currently using maribel's server, and plan to keep using that?
if so, then this issue can be closed

**Comment by 32th-System** [comment]
No we have our own server now

**Comment by n-rook** [comment]
We will stick with the vps
