### ISSUE TITLE
Add rules page or pages (including rules, terms of service, privacy policy)

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#52]
This should include:

- What types of runs are allowed to be uploaded
- What personal information we collect from users (nothing... except IP addresses probably)
- What we will ban you for (can be vague)

**Comment by raviddog** [comment]
personal information - anything that django stores as part of its user model (basically the user and admin_log tables i guess)
will delete upon request

**Comment by n-rook** [comment]
yeah that sounds about right. the only exception is ban info; if we have to ip ban somebody we aren't going to delete their ip immediately if they ask
