### ISSUE TITLE
Improve file replay uploading page to only make appropriate fields editable

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#56]
For example, difficulty should not be editable, and score should only be editable if it's counterstopped and the player is playing a counterstop game.

**Comment by raviddog** [comment]
i think add a button to edit/append additional data on the upload page

it should be assumed that the decoded data is correct
and only if something scrapes wrong should they be displayed in edit boxes
or eg. if its a counterstop (niche case)

**Comment by n-rook** [comment]
yeah, afaik even with desyncs the actual data in the replay file should be accurate
