### ISSUE TITLE
th07 stores stage splits for end-of-stage, everything else is the start of the stage

### ISSUE THREAD

**Issue by raviddog** [n-rook/thscoreboard#60]

**Comment by 32th-System** [comment]
so you mean that the scores are end of stage while everything else is start of stage?

**Comment by raviddog** [comment]
the game literally uses the previous stage score for the start score, theres no other way

**Comment by raviddog** [comment]
we will default to using end-of-stage values, pulling values from the next stage if necessary, and then having blank values for the final stage if there isn't any applicable data
