### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by raviddog** [n-rook/thscoreboard#63]

**Comment by raviddog** [comment]
Easy: more replays to search for edge cases
Hard: tests that involve saving and retrieving from the DB

**Comment by raviddog** [comment]
probably after we've implemented "nah this dont work" code
bad extraction, decompression, bad shottype info vs the game, etc

**Comment by n-rook** [comment]
going to close this one, imo it's too broad for anyone to take it on and know what they're supposed to do
