### ISSUE TITLE
Self-host web fonts

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#92]
We are currently using web fonts from Google's font delivery service. Web fonts are nice but some folks don't like Google, so we should probably self-host these fonts so Google doesn't have to be involved.

**Comment by 32th-System** [comment]
The actual creators of the fonts we use host them here:
- [Lato](https://www.latofonts.com/lato-free-fonts/)
- [EB Garamond](https://github.com/octaviopardo/EBGaramond12/tree/master/fonts/webfonts)

**Comment by n-rook** [comment]
Oh nice!
